package com.example.teacherforboss.presentation.ui.community.boss_talk.main

import androidx.lifecycle.ViewModel
import com.example.teacherforboss.presentation.ui.community.boss_talk.main.card.BossTalkMainCard
import java.time.LocalDateTime


class BossTalkMainViewModel : ViewModel() {

    val mockCardList = listOf<BossTalkMainCard>(
        BossTalkMainCard(
            title = "질문이 있습니다",
            content = "가나다라마박사 저는 누구누구인데요 이러이런 고민이 있습니당..",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "3",
            like_count = "2",
            comment_count = "4",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "폐업 직전에 마지막 희망이라도..",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 5, 30, 0, 0, 0),
            bookmark_count = "2",
            like_count = "3",
            comment_count = "4",
            liked = false,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "어쩌구저쩌구 저는 할 말이 많습니다 질문 많아요",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 4, 2, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = false,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "네번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 12, 24, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = false,
            bookmarked = false,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "다섯번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = false,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "여섯번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "일곱번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "여덟번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = false,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "아홉번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "열번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "열한번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "열두번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "열세번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "열네번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "열다섯번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "열여섯번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "열일곱번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "열여덟번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "열아홉번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "스무번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "스물한번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
        BossTalkMainCard(
            title = "스물두번째 질문입니다 ㅋㅋ",
            content = "어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라 어쩌구저쩌구 샬라샬라",
            created_at = LocalDateTime.of(2024, 6, 12, 0, 0, 0),
            bookmark_count = "111",
            like_count = "43",
            comment_count = "12",
            liked = true,
            bookmarked = true,
            post_id = 12341234,
        ),
    )
}
